export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const TOGGLE_LOGIN_TOOLTIP = "TOGGLE_LOGIN_TOOLTIP";
export const LOGOUT = "LOGOUT";

export const TOGGLE_MOBILE_MENU = "TOGGLE_MOBILE_MENU";

export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const GET_CATEGORY_LIST_SUCCESS = "GET_CATEGORY_LIST_SUCCESS";
export const GET_CATEGORY_LIST_FAILED = "GET_CATEGORY_LIST_FAILED";

export const GET_RECIPES_BY_CATEGORY_SUCCESS =
  "GET_RECIPES_BY_CATEGORY_SUCCESS";
export const GET_RECOMMENDED_RECIPE_SUCCESS = "GET_RECOMMENDED_RECIPE_SUCCESS";
export const UPDATE_RECIPE_LIST_BY_SEARCH = "UPDATE_RECIPE_LIST_BY_SEARCH";
